#!/bin/bash
# =============================================================================
# HestiaCP hook: v-delete-user
# Fired by HestiaCP after a user account is deleted.
# Cleans up all Bunny DNS zones that belonged to the deleted user.
# Requires mapping/users.json to be populated (run sync_all once if upgrading).
#
# Args: USER
# =============================================================================
USER="$1"

[ -z "$USER" ] && exit 0

PLUGIN=/usr/local/hestia/plugins/bunny-dns/bunny-dns.sh
[ -x "$PLUGIN" ] || exit 0

"$PLUGIN" delete_user "$USER"

exit 0
